In [22]:
#Creating a list of the years I wanna work on
years = list(range(1991,2026))

In [23]:
#The website I wanna webscrape
url_start = "https://www.basketball-reference.com/awards/awards_{}.html"

### Initially I am going to web scrape and get data for all the players who were MVP contenders

In [26]:
#Web scraping and downloading all html files for each year to my folder so I dont keep redownloading everytime
#Initially i just tried using regular pull requests but I kept getting blocked from bot detection, so i switched to selenium
from selenium import webdriver
import time
import os

os.makedirs("MVPs", exist_ok=True)

driver = webdriver.Chrome()

for year in years:
    url = url_start.format(year)
    driver.get(url)
    
    time.sleep(5)  # let Cloudflare + page load
    
    html = driver.page_source
    
    with open(f"MVPs/{year}.html", "w", encoding="utf-8") as f:
        f.write(html)
    
    print(f"Saved {year}")

driver.quit()

Saved 1991
Saved 1992
Saved 1993
Saved 1994
Saved 1995
Saved 1996
Saved 1997
Saved 1998
Saved 1999
Saved 2000
Saved 2001
Saved 2002
Saved 2003
Saved 2004
Saved 2005
Saved 2006
Saved 2007
Saved 2008
Saved 2009
Saved 2010
Saved 2011
Saved 2012
Saved 2013
Saved 2014
Saved 2015
Saved 2016
Saved 2017
Saved 2018
Saved 2019
Saved 2020
Saved 2021
Saved 2022
Saved 2023
Saved 2024
Saved 2025

In [28]:
#Using beautiful soup to parse my HTML files that I saved
from bs4 import BeautifulSoup

In [56]:
#Importing pandas because we want to turn the tables into dataframes for future machine learning
import pandas as pd

#Importing StringIO to convert an HTML string into a file for pandas
from io import StringIO

In [67]:
#Creating an empty list for each years dataframe
dfs = []

#Looping through each year to pull our html files from the folder to parse the html and turn it into a dataframe
for year in years:
    with open("MVPs/{}.html".format(year)) as f:
        page = f.read()

    #Intializing a beautiful soup class with the page string we made earlier as an html parser 
    soup = BeautifulSoup(page, "html.parser")

    #Removing the repeated header rows in the tables
    soup.find('tr',class_="over_header").decompose()

    #Finding the MVP tables by using its HTML ID
    mvptable = soup.find(id="mvp")

    #Turning the table into a dataframe
    mvp = pd.read_html(StringIO(str(mvptable)))[0]

    #Adding a year column to be able to identify the years later when we combine all the dataframes
    mvp["Year"] = year

    dfs.append(mvp)

In [69]:
#Combining the list of dataframes into a single dataframe
mvps = pd.concat(dfs)

In [74]:
mvps.head()

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,1,Michael Jordan,27,CHI,77,891,960,0.928,82,37.0,...,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321,1991
1,2,Magic Johnson,31,LAL,10,497,960,0.518,79,37.1,...,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251,1991
2,3,David Robinson,25,SAS,6,476,960,0.496,82,37.7,...,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264,1991
3,4,Charles Barkley,27,PHI,2,222,960,0.231,67,37.3,...,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258,1991
4,5,Karl Malone,27,UTA,0,142,960,0.148,82,40.3,...,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225,1991

In [75]:
mvp.tail()

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
7,7T,Anthony Edwards,23,MIN,0,12,1000,0.012,79,36.3,...,5.7,4.5,1.2,0.6,0.447,0.395,0.837,8.4,0.140,2025
8,9,Stephen Curry,36,GSW,0,2,1000,0.002,70,32.2,...,4.4,6.0,1.1,0.4,0.448,0.397,0.933,7.9,0.168,2025
9,10T,Jalen Brunson,28,NYK,0,1,1000,0.001,65,35.4,...,2.9,7.3,0.9,0.1,0.488,0.383,0.821,8.3,0.172,2025
10,10T,James Harden,35,LAC,0,1,1000,0.001,79,35.3,...,5.8,8.7,1.5,0.7,0.410,0.352,0.874,8.3,0.143,2025
11,10T,Evan Mobley,23,CLE,0,1,1000,0.001,71,30.5,...,9.3,3.2,0.9,1.6,0.557,0.370,0.725,9.0,0.200,2025

In [76]:
#Turning the dataframe into a csv for future use
mvps.to_csv("mvps.csv")

### Now I am going to webscrape and get the stats for all the players for each season

In [77]:
playerstats_url = "https://www.basketball-reference.com/leagues/NBA_{}_per_game.html"

#Repeating the same steps I used to webscrape earlier
os.makedirs("PlayerStats", exist_ok=True)

driver = webdriver.Chrome()

for year in years:
    url = playerstats_url.format(year)
    driver.get(url)
    
    time.sleep(5)  # let Cloudflare + page load
    
    html = driver.page_source
    
    with open(f"PlayerStats/{year}.html", "w", encoding="utf-8") as f:
        f.write(html)
    
    print(f"Saved {year}")

driver.quit()

Saved 1991
Saved 1992
Saved 1993
Saved 1994
Saved 1995
Saved 1996
Saved 1997
Saved 1998
Saved 1999
Saved 2000
Saved 2001
Saved 2002
Saved 2003
Saved 2004
Saved 2005
Saved 2006
Saved 2007
Saved 2008
Saved 2009
Saved 2010
Saved 2011
Saved 2012
Saved 2013
Saved 2014
Saved 2015
Saved 2016
Saved 2017
Saved 2018
Saved 2019
Saved 2020
Saved 2021
Saved 2022
Saved 2023
Saved 2024
Saved 2025

In [103]:
dfs = []

#Again I am going to loop through each year to pull our html files from the folder to parse the html and turn it into a dataframe
for year in years:
    with open("PlayerStats/{}.html".format(year)) as f:
        page = f.read()

    soup = BeautifulSoup(page, "html.parser")
    soup.find('tr',class_="thead").decompose()
    playertable = soup.find(id="per_game_stats")
    playerstats = pd.read_html(StringIO(str(playertable)))[0]
    playerstats["Year"] = year

    dfs.append(playerstats)

In [104]:
players = pd.concat(dfs)

In [90]:
#Turning our data into a csv for future ML
players.to_csv("PlayerStats.csv")

### Lastly I am going to web scrape all team data, this will be useful in helping me predict the MVP

In [110]:
#Scraping the data
team_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_standings.html"

for year in years:
    url = team_stats_url.format(year)
    driver.get(url)
    
    time.sleep(5)  # let Cloudflare + page load
    
    html = driver.page_source
    
    with open(f"Teams/{year}.html", "w", encoding="utf-8") as f:
        f.write(html)
        
    print(f"Saved {year}")

Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event)

Saved 1991
Saved 1992
Saved 1993
Saved 1994
Saved 1995
Saved 1996
Saved 1997
Saved 1998
Saved 1999
Saved 2000
Saved 2001
Saved 2002
Saved 2003
Saved 2004
Saved 2005
Saved 2006
Saved 2007
Saved 2008
Saved 2009
Saved 2010
Saved 2011
Saved 2012
Saved 2013
Saved 2014
Saved 2015
Saved 2016
Saved 2017
Saved 2018
Saved 2019
Saved 2020
Saved 2021
Saved 2022
Saved 2023
Saved 2024
Saved 2025

In [121]:
#Parsing the data with beautiful soup
dfs = []

#Again I am going to loop through each year to pull our html files from the folder to parse the html and turn it into a dataframe
for year in years:
    with open("Teams/{}.html".format(year)) as f:
        page = f.read()

    soup = BeautifulSoup(page, "html.parser")
    soup.find('tr',class_="thead").decompose()
    teamstable = soup.find(id="divs_standings_E")
    teamstable = pd.read_html(StringIO(str(teamstable)))[0]
    teamstable["Year"] = year
    teamstable["Team"] = teamstable["Eastern Conference"]
    del teamstable["Eastern Conference"]

    dfs.append(teamstable)

    soup = BeautifulSoup(page, "html.parser")
    soup.find('tr',class_="thead").decompose()
    teamstable = soup.find(id="divs_standings_W")
    teamstable = pd.read_html(StringIO(str(teamstable)), flavor="lxml")[0]
    teamstable["Year"] = year
    teamstable["Team"] = teamstable["Western Conference"]
    del teamstable["Western Conference"]

    dfs.append(teamstable)

In [122]:
teams = pd.concat(dfs)

In [125]:
teams.head(30)

,W,L,W/L%,GB,PS/G,PA/G,SRS,Year,Team
0,56,26,.683,—,111.5,105.7,5.22,1991,Boston Celtics*
1,44,38,.537,12.0,105.4,105.6,-0.39,1991,Philadelphia 76ers*
2,39,43,.476,17.0,103.1,103.3,-0.43,1991,New York Knicks*
3,30,52,.366,26.0,101.4,106.4,-4.84,1991,Washington Bullets
4,26,56,.317,30.0,102.9,107.5,-4.53,1991,New Jersey Nets
5,24,58,.293,32.0,101.8,107.8,-5.91,1991,Miami Heat
6,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,Central Division,1991,Central Division
7,61,21,.744,—,110.0,101.0,8.57,1991,Chicago Bulls*
8,50,32,.610,11.0,100.1,96.8,3.08,1991,Detroit Pistons*
9,48,34,.585,13.0,106.4,104.0,2.33,1991,Milwaukee Bucks*
10,43,39,.524,18.0,109.8,109.0,0.72,1991,Atlanta Hawks*
11,41,41,.500,20.0,111.7,112.1,-0.37,1991,Indiana Pacers*
12,33,49,.402,28.0,101.7,104.2,-2.33,1991,Cleveland Cavaliers
13,26,56,.317,35.0,102.8,108.0,-4.95,1991,Charlotte Hornets
0,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,Midwest Division,1991,Midwest Division
1,55,27,.671,—,107.1,102.6,4.30,1991,San Antonio Spurs*
2,54,28,.659,1.0,104.0,100.7,3.18,1991,Utah Jazz*
3,52,30,.634,3.0,106.7,103.2,3.27,1991,Houston Rockets*
4,31,51,.378,24.0,105.9,109.9,-3.79,1991,Orlando Magic
5,29,53,.354,26.0,99.6,103.5,-3.75,1991,Minnesota Timberwolves
6,28,54,.341,27.0,99.9,104.5,-4.27,1991,Dallas Mavericks
7,20,62,.244,35.0,119.9,130.8,-10.31,1991,Denver Nuggets
8,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,Pacific Division,1991,Pacific Division
9,63,19,.768,—,114.7,106.0,8.47,1991,Portland Trail Blazers*
10,58,24,.707,5.0,106.3,99.6,6.73,1991,Los Angeles Lakers*
11,55,27,.671,8.0,114.0,107.5,6.49,1991,Phoenix Suns*
12,44,38,.537,19.0,116.6,115.0,1.72,1991,Golden State Warriors*
13,41,41,.500,22.0,106.6,105.4,1.31,1991,Seattle SuperSonics*
14,31,51,.378,32.0,103.5,107.0,-3.16,1991,Los Angeles Clippers
15,25,57,.305,38.0,96.7,103.5,-6.27,1991,Sacramento Kings

In [124]:
#Saving it as a csv file
teams.to_csv("Teams.csv")